// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO5x_wjyUgk1RfNW7mqpanyPk-8Ea1feg',
    appId: '1:908431668742:web:99d71875080886edb3f587',
    messagingSenderId: '908431668742',
    projectId: 'door-knock-alert',
    authDomain: 'door-knock-alert.firebaseapp.com',
    storageBucket: 'door-knock-alert.appspot.com',
    measurementId: 'G-59BTPRZENY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZnYkfcKpXzfotSEF5eunzLWLsF098R8Y',
    appId: '1:908431668742:android:c6db49168d9d24a4b3f587',
    messagingSenderId: '908431668742',
    projectId: 'door-knock-alert',
    storageBucket: 'door-knock-alert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSAg-4z6UmTzl24NzwE-fyiUsRduDFIzQ',
    appId: '1:908431668742:ios:08bfc60842cb7ad9b3f587',
    messagingSenderId: '908431668742',
    projectId: 'door-knock-alert',
    storageBucket: 'door-knock-alert.appspot.com',
    iosClientId: '908431668742-ihg2e2tnah9k9jbpiubamh5d4avus5ng.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
